### ISSUE TITLE
Electron windows built error

### ISSUE THREAD

**Issue by debotos** [ronomon/opened#4]
It's working as expected in development mode. But only giving error when trying to build windows executable. macOS build is perfectly working.

I am using electron forge - ^6.0.0-beta.54

Please review. Thanks.

![Capture](https://user-images.githubusercontent.com/29367677/123775810-87618d00-d8f0-11eb-8b31-a0fe0dccb88d.PNG)

**Comment by debotos** [comment]
Found the solution - https://stackoverflow.com/a/52796884/8465770

**Comment by codal-mitalt** [comment]
I am facing the same issue. @debotos what works for you ?
